const moodQuotesData = [
  {
    mood: 'Stress',
    quotes: [
      'Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.',
      'Nothing is permanent in this wicked world, not even our troubles.',
      'Tension is who you think you should be. Relaxation is who you are.',
      'In times of stress, the best thing we can do for each other is to listen with our ears and our hearts and to be assured that our questions are just as important as our answers.',
      'Rule number one is, don’t sweat the small stuff. Rule number two is, it’s all small stuff.',
      'The greatest weapon against stress is our ability to choose one thought over another.',
      'There is more to life than increasing its speed.',
      'Within you, there is a stillness and a sanctuary to which you can retreat at any time and be yourself.',
      'The time to relax is when you don’t have time for it.',
      'It’s not stress that kills us, it is our reaction to it.',
      'Calm mind brings inner strength and self-confidence, so that’s very important for good health.',
      'The more tranquil a man becomes, the greater is his success, his influence, his power for good.',
      'Almost everything will work again if you unplug it for a few minutes, including you.',
      'Give your stress wings and let it fly away.',
      'Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.',
    ],
  },
  {
    mood: 'Fears',
    quotes: [
      'Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering.',
      'Everything you want is on the other side of fear.',
      'The only thing we have to fear is fear itself.',
      'Do one thing every day that scares you.',
      'Fear is only as deep as the mind allows.',
      'The cave you fear to enter holds the treasure you seek.',
      'Fear is a reaction. Courage is a decision.',
      'Fears are educated into us, and can, if we wish, be educated out.',
      'I have learned over the years that when one’s mind is made up, this diminishes fear.',
      'Fear keeps us focused on the past or worried about the future. If we can acknowledge our fear, we can realize that right now we are okay.',
      'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.',
      'You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.',
      'Fear is only temporary. Regrets last forever.',
      'Feel the fear and do it anyway.',
      'Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom.',
    ],
  },
  {
    mood: 'Helpless',
    quotes: [
      'When we are no longer able to change a situation, we are challenged to change ourselves.',
      'The only way out of the labyrinth of suffering is to forgive.',
      'The greatest act of courage is to be and to own all of who you are – without apology, without excuses, without masks to cover the truth of who you are.',
      'You can’t always control the circumstances – only how you react to those circumstances; you can always control your attitude and your efforts.',
      'Nothing is more beautiful than the smile that has struggled through the tears',
          ],
  },
  {
    mood: 'Exhausted',
    quotes: [
      'You never know how strong you are, until being strong is your only choice.',
      'Strength does not come from winning. Your struggles develop your strengths.',
      'Rest when you’re weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.',
      'When you come to the end of your rope, tie a knot and hang on.',
      'Fatigue is the common enemy of us all – so slow down, rest up, replenish, and refill.',
      'It is not the load that breaks you down, it’s the way you carry it.',
      'When you’re feeling your worst, that’s when you get to know yourself the best.',
      'The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.',
      'Difficult roads often lead to beautiful destinations.',
      'You are so much stronger than you think.',
      'Your current situation is not your final destination.',
      'In the middle of every difficulty lies opportunity.',
      'The struggle you’re in today is developing the strength you need for tomorrow.',
      'Believe you can and you’re halfway there.',
      'When you feel like giving up, just remember the reason why you held on for so long.',
    ],
  },
  {
    mood: 'Sadness',
    quotes: [
      'Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.',
      'Sadness flies away on the wings of time.',
      'There is no greater sorrow than to recall happiness in times of misery.',
      'Tears shed for another person are not a sign of weakness. They are a sign of a pure heart.',
      'In the depth of winter, I finally learned that there was in me an invincible summer.',
      'Sometimes, you have to let go to see if there was anything worth holding onto.',
      'Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.',
      'Sadness is but a wall between two gardens.',
      'It is better to have loved and lost, than never to have loved at all.',
      'Sadness is also a kind of defense.',
      'There are far, far better things ahead than any we leave behind.',
      'Sadness gives depth. Happiness gives height. Sadness gives roots. Happiness gives branches.',
      'The word ‘happiness’ would lose its meaning if it were not balanced by sadness.',
      'Keep your head up. God gives his hardest battles to his strongest soldiers.',
      'Sometimes it takes sadness to know happiness, noise to appreciate silence, and absence to value presence.',
    ],
  },
  {
    mood: 'Uncertainty',
    quotes: [
      'The only thing that makes life possible is permanent, intolerable uncertainty; not knowing what comes next.',
      'Embrace uncertainty. Some of the most beautiful chapters in our lives won’t have a title until much later.',
      'Trust the wait. Embrace the uncertainty. Enjoy the beauty of becoming.',
      'The quest for certainty blocks the search for meaning. Uncertainty is the very condition to impel man to unfold his powers.',
      'To be uncertain is to be uncomfortable, but to be certain is to be ridiculous.',
      'The desire for safety stands against every great and noble enterprise.',
      'Uncertainty is the fertile ground of pure creativity and freedom.',
    ],
    },
    {
    mood: 'Frustration',
    quotes: [
    'Frustration, although quite painful at times, is a very positive and essential part of success.',
    'The key to success is to focus our conscious mind on things we desire, not things we fear.',
    'You will face your greatest opposition when you are closest to your biggest miracle.',
    'Life is 10% what happens to you and 90% how you handle it.',
    'Your present circumstances don’t determine where you can go; they merely determine where you start.',
    'The only way to escape the personal corruption of praise is to go on working.',
    'Don’t let today’s disappointments cast a shadow on tomorrow’s dreams.',
    'Success is not built on success. It’s built on failure. It’s built on frustration. Sometimes it’s built on catastrophe.',
    'Life is not about how fast you run or how high you climb, but how well you bounce.',
    'Success is the ability to go from one failure to another with no loss of enthusiasm.',
    'In times of great stress or adversity, it’s always best to keep busy, to plow your anger and your energy into something positive.',
    'To conquer frustration, one must remain intensely focused on the outcome, not the obstacles.',
    'The road to success is lined with many tempting parking spaces.',
    'Don’t dwell on what went wrong. Instead, focus on what to do next. Spend your energy moving forward together towards an answer.',
    'It’s not about perfect. It’s about effort. And when you bring that effort every single day, that’s where transformation happens. That’s how change occurs.',
    ],
    },
    {
    mood: 'Procrastination',
    quotes: [
    'Procrastination is the thief of time, collar him.',
    'You don’t have to see the whole staircase, just take the first step.',
    'The secret of getting ahead is getting started.',
    'Do not wait; the time will never be ‘just right.’ Start where you stand, and work with whatever tools you may have at your command, and better tools will be found as you go along.',
    'The way to get started is to quit talking and begin doing.',
    'Your time is limited, don’t waste it living someone else’s life.',
    'The best time to plant a tree was 20 years ago. The second best time is now.',
    'You may delay, but time will not.',
    'A year from now you may wish you had started today.',
    'Someday is not a day of the week.',
    'Begin while others are procrastinating. Work while others are wishing.',
    'Procrastination is opportunity’s assassin.',
    'Action is the foundational key to all success.',
    'Great acts are made up of small deeds.',
    'You don’t have to be great to start, but you have to start to be great.',
    ],
    },
    ];
    
    export default moodQuotesData;
      


  