const quotesData = [
    {
      "author": "Plato",
      "quotes": [
         "Wise men speak because they have something to say; fools because they have to say something.",
      "At the touch of love, everyone becomes a poet.",
      "Courage is knowing what not to fear.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "Good actions give strength to ourselves and inspire good actions in others.",
      "One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors.",
      "Ignorance, the root and stem of all evil.",
      "Ideas are the source of all things.",
      "He who commits injustice is ever made more wretched than he who suffers it.",
      "Knowledge which is acquired under compulsion obtains no hold on the mind.",
      "Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.",
      "The measure of a man is what he does with power.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "Those who are able to see beyond the shadows and lies of their culture will never be understood, let alone believed, by the masses.",
      "The beginning is the most important part of the work.",
      "We do not learn, and that what we call learning is only a process of recollection.",
      "Ideas are the source of all things.",
      "Courage is knowing what not to fear.",
      "The heaviest penalty for declining to rule is to be ruled by someone inferior to yourself.",
      "At the touch of love, everyone becomes a poet.",
      "The first and greatest victory is to conquer yourself.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "Knowledge becomes evil if the aim be not virtuous.",
      "Better a little which is well done, than a great deal imperfectly.",
      "Human behavior flows from three main sources: desire, emotion, and knowledge.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors.",
      "The eyes of the soul of the multitudes are unable to endure the vision of the divine.",
      "Knowledge, which is acquired under compulsion, obtains no hold on the mind.",
      "The greatest wealth is to live content with little.",
      "Music and rhythm find their way into the secret places of the soul.",
      "The direction in which education starts a man will determine his future in life.",
      "All learning has an emotional base.",
      "Astronomy compels the soul to look upwards and leads us from this world to another.",
      "Ignorance, the root and stem of all evil.",
      "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.",
      "Those who are too smart to engage in politics are punished by being governed by those who are dumber.",
      "The learning and knowledge that we have, is, at the most, but little compared with that of which we are ignorant.",
      "Knowledge without justice ought to be called cunning rather than wisdom.",
      "Those who are able to see beyond the shadows and lies of their culture will never be understood, let alone believed, by the masses.",
      "The soul takes nothing with her to the next world but her education and her culture. At the beginning of the journey to the next world, one's education and culture can either provide the greatest assistance, or else act as the greatest burden, to the person who has just died.",
      "To be afraid of death is only another form of thinking that one is wise when one is not; it is to think that one knows what one does not know. No one knows whether death may not even turn out to be the greatest blessings of human beings.",
      "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
      "The measure of a man is what he does with power.",
      "All things will be produced in superior quantity and quality, and with greater ease, when each man works at a single occupation, in accordance with his natural gifts, and at the right moment, without meddling with anything else.",
      "We are twice armed if we fight with faith.",
      "Thinking: the talking of the soul with itself.",
      "The heaviest penalty for declining to rule is to be ruled by someone inferior to yourself.",
      "If women are expected to do the same work as men, we must teach them the same things.",
      "At the touch of love, everyone becomes a poet.",
      "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
      "Knowledge that is acquired under compulsion obtains no hold on the mind.",
      "He was a wise man who invented beer.",
      "There will be no end to the troubles of states, or of humanity itself, till philosophers become kings in this world, or till those we now call kings and rulers really and truly become philosophers, and political power and philosophy thus come into the same hands.",
      "The heaviest penalty for declining to rule is to be ruled by someone inferior to yourself.",
      "The good of a book lies in its being read. A book is made up of signs that speak of other signs, which in their turn speak of things. Without an eye to read them, a book contains signs that produce no concepts; therefore it is dumb.",
      "The madness of love is the greatest of heaven's blessings.",
      "At the touch of love, everyone becomes a poet."
  
      ]
    },
    {
      "author": "Friedrich Nietzsche",
      "quotes": [
        "He who has a why to live can bear almost any how.",
      "Without music, life would be a mistake.",
      "What does not kill me, makes me stronger.",
      "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
      "And those who were seen dancing were thought to be insane by those who could not hear the music.",
      "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.",
      "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.",
      "In heaven, all the interesting people are missing.",
      "Is man one of God's blunders? Or is God one of man's blunders?",
      "One must still have chaos in oneself to be able to give birth to a dancing star.",
      "He who would learn to fly one day must first learn to stand and walk and run and climb and dance; one cannot fly into flying.",
      "The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.",
      "There are no facts, only interpretations.",
      "The higher we soar the smaller we appear to those who cannot fly.",
      "Beware that, when fighting monsters, you yourself do not become a monster... for when you gaze long into the abyss. The abyss gazes also into you.",
      "It is hard enough to remember my opinions, without also remembering my reasons for them!",
      "To live is to suffer, to survive is to find some meaning in the suffering.",
      "All truly great thoughts are conceived while walking.",
      "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
      "The most common lie is that which one lies to himself; lying to others is relatively an exception.",
      "And we should consider every day lost on which we have not danced at least once. And we should call every truth false which was not accompanied by at least one laugh.",
      "What is good? All that heightens the feeling of power in man, the will to power, power itself.",
      "There are two different types of people in the world, those who want to know, and those who want to believe.",
      "The true man wants two things: danger and play. For that reason, he wants woman, as the most dangerous plaything.",
      "A thinker sees his own actions as experiments and questions--as attempts to find out something. Success and failure are for him answers above all.",
      "I cannot believe in a God who wants to be praised all the time.",
      "A good writer possesses not only his own spirit but also the spirit of his friends.",
      "The best weapon against an enemy is another enemy.",
      "He who fights with monsters should be careful lest he thereby become a monster. And if thou gaze long into an abyss, the abyss will also gaze into thee.",
      "All things are subject to interpretation. Whichever interpretation prevails at a given time is a function of power and not truth.",
      "There is always some madness in love. But there is also always some reason in madness.",
      "What is great in man is that he is a bridge and not an end: what can be loved in man is that he is an overture and a going under.",
      "In war, the first casualty is the truth.",
      "Man is the cruelest animal.",
      "We love life, not because we are used to living but because we are used to loving.",
      "God is dead. God remains dead. And we have killed him. How shall we comfort ourselves, the murderers of all murderers?",
      "The essence of all beautiful art, all great art, is gratitude.",
      "The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself."
      ]
    },
  {
      "author": "Marcus Aurelius",
      "quotes": [
        "The happiness of your life depends upon the quality of your thoughts.",
      "The universe is change; our life is what our thoughts make it.",
      "Dwell on the beauty of life. Watch the stars, and see yourself running with them.",
      "The best revenge is to be unlike him who performed the injury.",
      "The soul becomes dyed with the color of its thoughts.",
      "The impediment to action advances action. What stands in the way becomes the way.",
      "The art of living is more like wrestling than dancing.",
      "If it is not right, do not do it; if it is not true, do not say it.",
      "The wise man sees in the misfortune of others what he avoids.",
      "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.",
      "You have power over your mind - not outside events. Realize this, and you will find strength.",
      "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
      "The universe is change; our life is what our thoughts make it.",
      "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
      "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.",
      "It is not death that a man should fear, but he should fear never beginning to live.",
      "The only wealth which you will keep forever is the wealth you have given away.",
      "He who lives in harmony with himself lives in harmony with the universe.",
      "The happiness of your life depends upon the quality of your thoughts.",
      "If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed.",
      "The art of living is more like wrestling than dancing.",
      "Objective judgment, now at this very moment. Unselfish action, now at this very moment. Willing acceptance—now at this very moment—of all external events. That’s all you need.",
      "The universe is change; life is opinion.",
      "What we do now echoes in eternity.",
      "The happiness of your life depends upon the quality of your thoughts.",
      "The soul becomes dyed with the color of its thoughts.",
      "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
      "The best revenge is to be unlike him who performed the injury.",
      "Our life is what our thoughts make it.",
      "Life is neither good nor evil, but only a place for good and evil.",
      "The greatest wealth is to live content with little.",
      "The happiness of your life depends upon the quality of your thoughts.",
      "The happiness of your life depends upon the quality of your thoughts.",
      "Loss is nothing else but change, and change is Nature's delight.",
      "The universe is change; our life is what our thoughts make it.",
      "The only wealth which you will keep forever is the wealth you have given away.",
      "He who lives in harmony with himself lives in harmony with the universe.",
      "The best revenge is to be unlike him who performed the injury." 
      ]
    },
  
  {
      "author": "Carl Jung",
      "quotes": [
         "I am not what happened to me, I am what I choose to become.",
    "Knowing your own darkness is the best method for dealing with the darknesses of other people.",
  "Your vision will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.",
   "The greatest and most important problems of life are all fundamentally insoluble. They can never be solved but only outgrown.",
  "As far as we can discern, the sole purpose of human existence is to kindle a light in the darkness of mere being.",
  "Where love rules, there is no will to power, and where power predominates, love is lacking. The one is the shadow of the other.",
  "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.",
  "Loneliness does not come from having no people about one, but from being unable to communicate the things that seem important to oneself, or from holding certain views which others find inadmissible.",
  "The creation of something new is not accomplished by the intellect but by the play instinct acting from inner necessity. The creative mind plays with the objects it loves.",
  "As far as we can discern, the sole purpose of human existence is to kindle a light in the darkness of mere being.",
    "The greatest and most important problems of life are all fundamentally insoluble. They can never be solved but only outgrown.",
     "Everything that irritates us about others can lead us to an understanding of ourselves.",
     "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
    "The pendulum of the mind oscillates between sense and nonsense, not between right and wrong.",
    "The shoe that fits one person pinches another; there is no recipe for living that suits all cases.",
    "There is no coming to consciousness without pain.",
    "Show me a sane man and I will cure him for you.",
    "In all chaos there is a cosmos, in all disorder a secret order.",
    "An understanding heart is everything in a teacher, and cannot be esteemed highly enough.",
    "The privilege of a lifetime is to become who you truly are.",
    "Who has fully realized that history is not contained in thick books but lives in our very blood?",
    "Man needs difficulties; they are necessary for health.",
    "The least of things with a meaning is worth more in life than the greatest of things without it.",
    "A man who has not passed through the inferno of his passions has never overcome them.",
    "In my case, Pilgrim's Progress consisted in my having to climb down a thousand ladders until I could reach out my hand to the little clod of earth that I am.",
    "One looks back with appreciation to the brilliant teachers, but with gratitude to those who touched our human feelings.",
    "Mistakes are, after all, the foundations of truth, and if a man does not know what a thing is, it is at least an increase in knowledge if he knows what it is not.",
    "There is no birth of consciousness without pain.",
    "We cannot change anything until we accept it. Condemnation does not liberate, it oppresses.",
    "To ask the right question is already half the solution of a problem.",
    "Nobody, as long as he moves about among the chaotic currents of life, is without trouble.",
    "A dream that is not understood remains a mere occurrence; understood, it becomes a living experience."
      ]
    },
  
  
  ];
  
  export default quotesData;
  